language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  global:
    - RMQ_VER=3.1.5

before_script:
  - composer self-update
  - ./tests/bin/run_rabbitmq.sh
  - ./tests/bin/create_mapping

script: phpunit
