language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
    - LIBRABBITMQ_VERSION=master

services:
    - rabbitmq

before_script:
  - sh -c "git clone git://github.com/alanxz/rabbitmq-c.git"
  - sh -c "cd rabbitmq-c && git checkout ${LIBRABBITMQ_VERSION}"
  - sh -c "cd rabbitmq-c && git submodule init && git submodule update"
  - sh -c "cd rabbitmq-c && autoreconf -i && ./configure && make && sudo make install"
  - echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install
  - sh -c "./tests/bin/init_rabbit.sh"

script: phpunit

notifications:
  email:
    - olivier.dolbeau@blablacar.com
